name: Scan

on:
  push:
  workflow_dispatch:
    inputs:
      apkurl:
        description: "apkurl地址"
        default: "https://github.com/AoThen/TVBoxAPP/releases/download/mlabalabala-box-20240919-1305/TVBox_mlabalabala_20240919-1305.apk"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install
        run: |
          sudo apt update
          sudo apt install openjdk-11-jdk unzip -y
          java -version
          sudo apt-get update && sudo apt-get install -y apktool
          wget https://github.com/skylot/jadx/releases/download/v1.5.1/jadx-1.5.1.zip
          unzip -o jadx-1.5.1.zip
          cp apk2url.sh bin/apk2url
          cd bin
          chmod +x jadx
          chmod +x apk2url


      - name: Check
        if: ${{ inputs.apkurl }}
        run: |
          cd bin
          wget -O test.apk ${{ inputs.apkurl }}
          apk2url test.apk
          cat *_uniq.txt
          cat *_endpoints.txt
          
      - name: Upload
        uses: actions/upload-artifact@main
        if: ${{ inputs.apkurl }}
        with:
          name: applog
          path: |
            *_uniq.txt
            *_endpoints.txt

  clean:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: AoThen/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1