name: Scan

on:
#   push:
  workflow_dispatch:
    inputs:
      apkurl:
        description: "apkurl地址"
        default: "apk"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install
        run: |
          sudo apt update
          sudo apt install openjdk-11-jdk unzip -y
          java -version
          sudo apt-get update && sudo apt-get install -y apktool
          wget https://github.com/skylot/jadx/releases/download/v1.5.1/jadx-1.5.1.zip
          unzip jadx-1.5.1.zip
          sudo mv bin/jadx /usr/local/bin/
          sudo chmod +x /usr/local/bin/jadx
          sudo cp lib/jadx-1.5.1-all.jar /usr/local/lib/
          cp apk2url.sh /usr/bin/apk2url 2>/dev/null
          chmod +x /usr/bin/apk2url 2>/dev/null


      - name: Check
        if: ${{ inputs.apkurl }}
        run: |
          wget -O test.apk ${{ inputs.apkurl }}
          apk2url test.apk
          
      - name: Upload
        uses: actions/upload-artifact@main
        if: ${{ inputs.apkurl }}
        with:
          name: applog
          path: |
            *_uniq.txt
            *_endpoints.txt

  clean:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: AoThen/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1